export const LOCALIZATION = {
	es: {
		viewTitle: "Combat Ledger",
		openCommand: "Abrir Combat Ledger",
		round: "Ronda",
		nextTurn: "▶ Siguiente turno",
		load: "＋ Cargar",
		reset: "↺ Reset",
		resetConfirm: "¿Reiniciar batalla? Se perderá el estado actual.",
		emptyState: "Sin combatientes. Pulsa «Cargar» para añadir notas.",
		init: "Init",
		ac: "CA",
		hp: "PV",
		shield: "Escudo",
		xp: "XP",
		playerView: "Vista de jugadores",
		fullscreen: "Pantalla completa",
		damageHeal: "⚔ Daño / Curar",
		status: "◈ Estado",
		note: "✎ Nota",
		action: "⚡ Acción",
		defeat: "Derrotar",
		revive: "Revivir",
		editInitiative: "Editar iniciativa",
		removeTitle: "Quitar del combate",
		dmgModalTitle: "Daño / Curación",
		dmgModalQty: "Cantidad",
		dmgModalHeal: "♥ Curar",
		dmgModalDmg: "⚔ Daño",
		dmgModalUseShield: "Absorber daño con escudo",
		dmgModalNoShield: "Sin escudo disponible",
		condModalTitle: "Condiciones",
		condModalApply: "Aplicar",
		condModalDurationPlaceholder: "Duración en rondas",
		noteModalTitle: "Nota rápida",
		noteModalPlaceholder: "Anota algo sobre este combatiente...",
		noteModalSave: "Guardar",
		actionModalTitle: "Acción",
		actionModalDamagePlaceholder: "Daño a aplicar",
		actionModalShieldLabel: "Permitir que el escudo absorba daño",
		actionModalNoCondition: "Sin condición",
		actionModalNotePlaceholder: "Efecto o nota contextual",
		actionModalApply: "Aplicar acción",
		graveyardTitle: "Bajas / Cementerio",
		graveyardEmpty: "No hay combatientes derrotados.",
		graveyardPendingXp: "XP pendiente",
		graveyardAssignedXp: "XP repartida",
		graveyardDistributeAll: "Repartir entre PCs",
		graveyardGiveTo: "Dar a",
		graveyardXpPlaceholder: "XP a repartir",
		graveyardExpiredTurn: "Toca al siguiente",
		playerViewTitle: "Panel de jugadores",
		playerViewSubtitle: "Orden de turno, combatiente activo y condiciones visibles",
		boardTitle: "Tablero",
		boardCenter: "Centrar tokens",
		boardSave: "Guardar layout",
		boardLoad: "Cargar layout",
		boardClear: "Limpiar layout",
		boardBackground: "Fondo",
		boardHide: "Ocultar",
		boardReveal: "Mostrar",
		boardHidden: "Oculto a jugadores",
		boardSavePrompt: "Nombre del layout a guardar",
		boardLoadPrompt: "Escribe el nombre exacto del layout a cargar",
		boardDeletePrompt: "Escribe el nombre exacto del layout a eliminar",
		boardNoLayouts: "No hay layouts guardados.",
		alertTurnStart: "Turno de",
		alertConditionExpired: "Condición expirada",
		alertDefeated: "Derrotado",
		alertTimerExpired: "Tiempo agotado",
		pickModalTitle: "Selecciona combatientes",
		pickModalSearch: "Buscar nota...",
		pickModalLoad: "Cargar al combate",
		pickModalCancel: "Cancelar",
		pickModalSelectMin: "Selecciona al menos una nota.",
		
		// Settings
		settingsTitle: "Combat Ledger — Configuración",
		settingsLanguageName: "Idioma / Language",
		settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
		settingsFieldsTitle: "Campos de combatiente",
		settingsFieldsDesc: "Escribe el nombre exacto de la propiedad YAML que usas en tus notas.",
		settingsInitName: "Iniciativa",
		settingsInitDesc: "Propiedad para el valor de iniciativa",
		settingsHpName: "PV actuales",
		settingsHpDesc: "Propiedad para puntos de vida actuales (se usa también como máximo si no hay hp_max)",
		settingsHpMaxName: "PV máximos",
		settingsHpMaxDesc: "Propiedad para puntos de vida máximos",
		settingsShieldName: "Escudo",
		settingsShieldDesc: "Propiedad para el valor de escudo o puntos temporales. Déjalo vacío si no usas escudo.",
		settingsXpName: "Experiencia",
		settingsXpDesc: "Propiedad para la experiencia del personaje o del enemigo.",
		settingsAvatarName: "Avatar",
		settingsAvatarDesc: "Propiedad YAML con una ruta o URL de imagen para mostrar en la tarjeta.",
		settingsIconName: "Icono",
		settingsIconDesc: "Propiedad YAML con un icono o emoji alternativo para el avatar.",
		settingsAcName: "Clase de Armadura / Defensa",
		settingsAcDesc: "Propiedad para CA o defensa",
		settingsTypeName: "Tipo",
		settingsTypeDesc: "Propiedad para el tipo: \"PC\", \"Enemy\" o \"NPC\"",
		settingsExtraName: "Campos extra",
		settingsExtraDesc: "Propiedades numéricas adicionales separadas por comas (ej. mp,stamina,stress)",
		settingsConditionsFieldName: "Campo de condiciones",
		settingsConditionsFieldDesc: "Propiedad YAML donde se sincronizan las condiciones activas.",
		settingsRealtimeTitle: "Sincronización y daño",
		settingsRealtimeSyncName: "Sincronización en tiempo real",
		settingsRealtimeSyncDesc: "Actualiza automáticamente la nota original al cambiar PV, iniciativa, condiciones, escudo o extras.",
		settingsRealtimeModeName: "Sincronizar a",
		settingsRealtimeModeDesc: "Limita la sincronización a personajes jugadores o aplícala a todos los combatientes.",
		settingsRealtimeModePc: "Solo PC",
		settingsRealtimeModeAll: "PC y NPC/Enemigos",
		settingsShieldAbsorbName: "El escudo absorbe daño",
		settingsShieldAbsorbDesc: "Cuando esté activo, el daño se resta primero del escudo antes de afectar los PV.",
		settingsTimerTitle: "Temporizador de turno",
		settingsTimerEnabledName: "Habilitar temporizador visual",
		settingsTimerEnabledDesc: "Muestra un temporizador del turno activo en la barra superior.",
		settingsTimerSecondsName: "Duración del turno (segundos)",
		settingsTimerSecondsDesc: "Tiempo máximo del turno antes de mostrar el aviso para pasar al siguiente.",
		settingsPlayerHpName: "Mostrar PV en vista de jugadores",
		settingsPlayerHpDesc: "Si está desactivado, la vista de jugadores oculta los valores exactos de PV.",
		settingsBoardTitle: "Tablero visual",
		settingsBoardGridName: "Mostrar grid por defecto",
		settingsBoardGridDesc: "Activa una cuadrícula visual en el tablero de combate.",
		settingsBoardSnapName: "Ajustar tokens al grid",
		settingsBoardSnapDesc: "Al arrastrar tokens, se alinean automáticamente a la cuadrícula.",
		settingsBoardGridSizeName: "Tamaño del grid",
		settingsBoardGridSizeDesc: "Tamaño en píxeles de cada celda del tablero.",
		settingsBoardBackgroundName: "Fondo por defecto del tablero",
		settingsBoardBackgroundDesc: "Ruta del vault o URL de imagen usada como fondo inicial del tablero.",
		settingsCondTitle: "Condiciones / Estados",
		settingsCondColorDesc: "Personaliza el nombre y color de cada estado. El color se aplica al badge en la vista de combate.",
		settingsCondAddBtn: "＋ Añadir condición",
		settingsCondDeleteBtn: "Eliminar",
		settingsCondNamePlaceholder: "Nombre del estado",
		settingsCondColorLabel: "Color",
		settingsFolderTitle: "Carpeta de combatientes (opcional)",
		settingsFolderFieldName: "Ruta de carpeta",
		settingsFolderFieldDesc: "Si indicas una carpeta (ej. Campaña/Criaturas), al pulsar «Cargar» cargará todas las notas de esa carpeta automáticamente. Déjalo vacío para seleccionar manualmente.",
		
		// Logging Settings & UI
		logTitle: "Registro de Combate (Log)",
		logEnabledName: "Habilitar registro de combate",
		logEnabledDesc: "Registra el progreso del combate en una nota de Markdown.",
		logModeName: "Modo de registro",
		logModeDesc: "Elige si registrar en una nota nueva o en una existente.",
		logModeNew: "Nueva nota",
		logModeExisting: "Nota existente",
		logModeAsk: "Preguntar siempre",
		logHeaderName: "Encabezado del Registro",
		logHeaderDesc: "El encabezado Markdown (ej. ## Registro de Combate) debajo del cual se guardará el log.",
		logFileNameName: "Nombre de archivo para nuevas notas",
		logFileNameDesc: "Nombre/Ruta del archivo para nuevas notas de log (puedes usar {date} para la fecha actual).",
		logSelectFile: "Selecciona la nota para el log",
		logHeaderPlaceholder: "## Registro de Combate",
		logStarted: "Combate iniciado.",
		logEnded: "Combate finalizado/reiniciado.",
		logActiveLogFile: "Archivo de registro activo",
		logSelectLogFileButton: "Configurar Registro",
		logConfigureTitle: "Configurar Registro de Combate",
		logChooseExistingFile: "Buscar nota existente...",
		logExistingFilePath: "Ruta de la nota existente",
		logCreateNewFile: "Crear nueva nota de registro",
		logSelectNoteNotice: "Por favor selecciona o crea una nota para el registro.",
		logNewNoteDefaultName: "Registro de Combate {date}",
		logModalHeading: "Nota de Registro",
		logHeadingDesc: "Selecciona dónde quieres registrar este combate:",
		logButtonNew: "Crear Nueva Nota",
		logButtonExisting: "Usar Nota Existente",
		logButtonNoLog: "No registrar",
	},
	en: {
		viewTitle: "Combat Ledger",
		openCommand: "Open Combat Ledger",
		round: "Round",
		nextTurn: "▶ Next turn",
		load: "＋ Load",
		reset: "↺ Reset",
		resetConfirm: "Reset battle? Current state will be lost.",
		emptyState: "No combatants. Click 'Load' to add notes.",
		init: "Init",
		ac: "AC",
		hp: "HP",
		shield: "Shield",
		xp: "XP",
		playerView: "Player view",
		fullscreen: "Fullscreen",
		damageHeal: "⚔ Damage / Heal",
		status: "◈ Status",
		note: "✎ Note",
		action: "⚡ Action",
		defeat: "Defeat",
		revive: "Revive",
		editInitiative: "Edit initiative",
		removeTitle: "Remove from battle",
		dmgModalTitle: "Damage / Healing",
		dmgModalQty: "Amount",
		dmgModalHeal: "♥ Heal",
		dmgModalDmg: "⚔ Damage",
		dmgModalUseShield: "Let shield absorb damage",
		dmgModalNoShield: "No shield available",
		condModalTitle: "Conditions",
		condModalApply: "Apply",
		condModalDurationPlaceholder: "Duration in rounds",
		noteModalTitle: "Quick note",
		noteModalPlaceholder: "Write something about this combatant...",
		noteModalSave: "Save",
		actionModalTitle: "Action",
		actionModalDamagePlaceholder: "Damage to apply",
		actionModalShieldLabel: "Allow shield to absorb damage",
		actionModalNoCondition: "No condition",
		actionModalNotePlaceholder: "Effect or contextual note",
		actionModalApply: "Apply action",
		graveyardTitle: "Graveyard",
		graveyardEmpty: "There are no defeated combatants.",
		graveyardPendingXp: "Pending XP",
		graveyardAssignedXp: "Assigned XP",
		graveyardDistributeAll: "Split among PCs",
		graveyardGiveTo: "Give to",
		graveyardXpPlaceholder: "XP to award",
		graveyardExpiredTurn: "Next turn",
		playerViewTitle: "Player dashboard",
		playerViewSubtitle: "Turn order, active combatant, and visible conditions",
		boardTitle: "Board",
		boardCenter: "Center tokens",
		boardSave: "Save layout",
		boardLoad: "Load layout",
		boardClear: "Clear layout",
		boardBackground: "Background",
		boardHide: "Hide",
		boardReveal: "Reveal",
		boardHidden: "Hidden from players",
		boardSavePrompt: "Layout name to save",
		boardLoadPrompt: "Enter the exact layout name to load",
		boardDeletePrompt: "Enter the exact layout name to delete",
		boardNoLayouts: "There are no saved layouts.",
		alertTurnStart: "Turn of",
		alertConditionExpired: "Condition expired",
		alertDefeated: "Defeated",
		alertTimerExpired: "Time expired",
		pickModalTitle: "Select combatants",
		pickModalSearch: "Search note...",
		pickModalLoad: "Load to battle",
		pickModalCancel: "Cancel",
		pickModalSelectMin: "Select at least one note.",
		
		// Settings
		settingsTitle: "Combat Ledger — Settings",
		settingsLanguageName: "Idioma / Language",
		settingsLanguageDesc: "Selecciona el idioma de la interfaz (Select the interface language)",
		settingsFieldsTitle: "Combatant Fields",
		settingsFieldsDesc: "Write the exact name of the YAML property you use in your notes.",
		settingsInitName: "Initiative",
		settingsInitDesc: "Property for the initiative value",
		settingsHpName: "Current HP",
		settingsHpDesc: "Property for current hit points (also used as max if hp_max is missing)",
		settingsHpMaxName: "Max HP",
		settingsHpMaxDesc: "Property for maximum hit points",
		settingsShieldName: "Shield",
		settingsShieldDesc: "Property for shield or temporary hit points. Leave empty if unused.",
		settingsXpName: "Experience",
		settingsXpDesc: "Property for character or enemy experience.",
		settingsAvatarName: "Avatar",
		settingsAvatarDesc: "YAML property with an image path or URL to display on the card.",
		settingsIconName: "Icon",
		settingsIconDesc: "YAML property with an alternate icon or emoji for the avatar.",
		settingsAcName: "Armor Class / Defense",
		settingsAcDesc: "Property for AC or defense",
		settingsTypeName: "Type",
		settingsTypeDesc: "Property for type: \"PC\", \"Enemy\" or \"NPC\"",
		settingsExtraName: "Extra fields",
		settingsExtraDesc: "Additional numeric properties separated by commas (e.g. mp,stamina,stress)",
		settingsConditionsFieldName: "Conditions field",
		settingsConditionsFieldDesc: "YAML property where active conditions are synchronized.",
		settingsRealtimeTitle: "Sync and damage",
		settingsRealtimeSyncName: "Real-time sync",
		settingsRealtimeSyncDesc: "Automatically updates the original note when HP, initiative, conditions, shield, or extras change.",
		settingsRealtimeModeName: "Sync targets",
		settingsRealtimeModeDesc: "Limit synchronization to player characters or apply it to all combatants.",
		settingsRealtimeModePc: "PC only",
		settingsRealtimeModeAll: "PC and NPC/Enemies",
		settingsShieldAbsorbName: "Shield absorbs damage",
		settingsShieldAbsorbDesc: "When enabled, damage is removed from shield before it affects HP.",
		settingsTimerTitle: "Turn timer",
		settingsTimerEnabledName: "Enable visual timer",
		settingsTimerEnabledDesc: "Shows a timer for the active turn in the top bar.",
		settingsTimerSecondsName: "Turn duration (seconds)",
		settingsTimerSecondsDesc: "Maximum turn time before showing the prompt to move on.",
		settingsPlayerHpName: "Show HP in player view",
		settingsPlayerHpDesc: "If disabled, the player view hides exact HP values.",
		settingsBoardTitle: "Visual board",
		settingsBoardGridName: "Show grid by default",
		settingsBoardGridDesc: "Enables a visual grid on the combat board.",
		settingsBoardSnapName: "Snap tokens to grid",
		settingsBoardSnapDesc: "Dragging tokens aligns them automatically to the grid.",
		settingsBoardGridSizeName: "Grid size",
		settingsBoardGridSizeDesc: "Pixel size of each board cell.",
		settingsBoardBackgroundName: "Default board background",
		settingsBoardBackgroundDesc: "Vault path or image URL used as the initial board background.",
		settingsCondTitle: "Conditions / States",
		settingsCondColorDesc: "Customize the name and color of each status. The color is applied to the badge in the combat view.",
		settingsCondAddBtn: "＋ Add condition",
		settingsCondDeleteBtn: "Delete",
		settingsCondNamePlaceholder: "Status name",
		settingsCondColorLabel: "Color",
		settingsFolderTitle: "Combatant Folder (optional)",
		settingsFolderFieldName: "Folder path",
		settingsFolderFieldDesc: "If you specify a folder (e.g. Campaign/Creatures), clicking 'Load' will load all notes in that folder automatically. Leave empty to select manually.",
		
		// Logging Settings & UI
		logTitle: "Combat Log (Log)",
		logEnabledName: "Enable combat logging",
		logEnabledDesc: "Log combat progress into a Markdown note.",
		logModeName: "Logging mode",
		logModeDesc: "Choose whether to log in a new note or an existing one.",
		logModeNew: "New note",
		logModeExisting: "Existing note",
		logModeAsk: "Always ask",
		logHeaderName: "Log Header",
		logHeaderDesc: "The Markdown header (e.g. ## Combat Log) under which the log will be saved.",
		logFileNameName: "File name for new notes",
		logFileNameDesc: "File name/path for new log notes (you can use {date} for current date).",
		logSelectFile: "Select note for log",
		logHeaderPlaceholder: "## Combat Log",
		logStarted: "Combat started.",
		logEnded: "Combat ended/reset.",
		logActiveLogFile: "Active log file",
		logSelectLogFileButton: "Configure Log",
		logConfigureTitle: "Configure Combat Log",
		logChooseExistingFile: "Search existing note...",
		logExistingFilePath: "Existing note path",
		logCreateNewFile: "Create new log note",
		logSelectNoteNotice: "Please select or create a note for logging.",
		logNewNoteDefaultName: "Combat Log {date}",
		logModalHeading: "Log Note",
		logHeadingDesc: "Select where you want to log this combat:",
		logButtonNew: "Create New Note",
		logButtonExisting: "Use Existing Note",
		logButtonNoLog: "Do not log",
	}
};
